# Generated by Django 3.0.7 on 2020-07-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200702_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hotel_Main_Img',
            new_name='Upload_Picture',
        ),
    ]
