# Generated by Django 3.0.7 on 2020-07-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200703_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Upload_Picture',
            new_name='hotel_Main_Img',
        ),
    ]
